### ISSUE TITLE
Issue sharing planets on Mush en

### ISSUE THREAD

**Issue by vincentraulic** [badconker/ctrl-w#23]
If i click on the button share to share plants with the Astro Terminal open, and the focus on chat, nothing happen, i can't share plants. It's working on Mush fr.

**Comment by vincentraulic** [comment]
Toujours pas bon (testé aujourdui le 14/01/15), appuyer sur les deux boutons n'a aucun effet dans le chat

**Comment by badconker** [comment]
Je le mettrai quand je penserai avoir corrigé le problème. Le truc c'est que joue pas souvent sur le version EN :}

**Comment by badconker** [comment]
Normalement corrigé par ce commit : d1566e09ec75b0ae6125ccf141114037bc06e7f3.
