### ISSUE TITLE
Grunt pour fragmenter le code en fichier

### ISSUE THREAD

**Issue by FlorianPerrot** [badconker/ctrl-w#30]
Bonjour,

Connais tu [Grunt](http://gruntjs.com/) ?
Il permettrait de fragmenter le code en plusieurs fichiers et gagner énormément en lisibilité.
De plus il pourrait minifier le js automatiquement.

Si ça t’intéresse je pourrais m'occuper de faire le script Grunt et de déplacer les bouts de code dans des fichiers.

Florian Perrot

**Comment by badconker** [comment]
Oui, je connais mais j'utilise plutôt Gulp.

C'est une bonne idée en effet. 

Après faut bien réfléchir au découpage. Genre un fichier pour chaque tabs, un pour les paramètres en début de fichier, peut être aussi séparer les différent code css (et genre le \ en fin de ligne qui se met automatiquement via grunt/gulp, ce serait cool ça) etc... Hésite pas à me demander mon avis.

Si tu veux t'en charger pas de soucis mais c'est du boulot. Cependant je préférerais Gulp plutôt que Grunt si possible :}

Par contre est ce que les fichiers source map fonctionnent avec un userscript sous Firefox ? Faudrait tester ça en priorité parce que sinon ça risque d'être coton le débuggage. x)

**Comment by FlorianPerrot** [comment]
J'ai commencé, mais c'est beaucoup plus compliqué que prevu...

Pour faire un truc plus propre il faurait tout héberger sur Github
cf : http://christopheducamp.com/2013/12/21/demarrer-avec-pages-github/
de cette façon il nous serait possible d'extraire le css du code JS qui, il faut dire, n'est pas très jolie.
Ça complique juste un peu le développement du code css.

**Comment by badconker** [comment]
A part quelques images, il y a déjà tout sur Github y compris des fichiers css/js externes.
Qu'apporte les pages Github ?

**Comment by FlorianPerrot** [comment]
Il faut obligatoirement héberger les feuilles CSS pour pouvoir les séparés du js, donc dans une balise <link href="URL_GITHUB"/>

**Comment by badconker** [comment]
Mais c'est déjà le cas comme pour par exemple [ce fichier](https://github.com/badconker/ctrl-w/blob/master/lib/jquery.jgrowl.css) qui est importé via [cette ligne](https://github.com/badconker/ctrl-w/blob/master/CTRLW.user.js#L15)

**Comment by FlorianPerrot** [comment]
Ahhh oui, pk on n'utilise pas ça pour le [CustomMenu](https://github.com/badconker/ctrl-w/blob/master/CTRLW.user.js#L1064), [bubble](https://github.com/badconker/ctrl-w/blob/master/CTRLW.user.js#L1981) et [Ingame](https://github.com/badconker/ctrl-w/blob/master/CTRLW.user.js#L1165) ?

**Comment by badconker** [comment]
C'était à la base comme ça, j'avais la flemme d'externaliser mais surtout les extensions tampermonkey/Greasemonkey ne mettent pas toujours à jour les fichiers externes lors d'une mise à jour du script. C'est pour ça que pour une lib qui change jamais ça va mais pour du css lié directement au script, c'est plus embetant.

**Comment by FlorianPerrot** [comment]
Je pense avoir une version pas trop mal j'ai ajouter les modifs de la version 0.35.20 - [Voir ici](https://github.com/FlorianPerrot/ctrl-w/tree/dev)
J'ai regroupé quelques fonctions, mais pour le moment c'est très simple. Le gross du travail sera sur tabs/playing.js 
Si ça te va je fais un pull-request

**Comment by ajoah** [comment]
C'est un peu trop découpé à mon gout. Une fonction (ou presque) par fichier c'est un peu tout much ^^. Par exemple pourquoi ne pas mettre l'objet Game dans un seul fichier ? Mais tu as fais le plus gros, je vais reprendre ton travail et modifier quelques trucs merci :D Pour être à jour de la version 0.35.20 tu à checké tous les commits et copier les changements à la main sur ta version depuis la version 0.35.19b2 oO?

**Comment by FlorianPerrot** [comment]
Cette façon de découpé les fonctions est directement inspiré des frameworks (Plus particulièrement de Symfony et backbonesJS) faire un fichier "Game" serait moins pratique. Y a quelques trucs à changer comme le dossiers "main/utils" et les fichiers en vrac à la racine du dossier "main". 

Pour le passé en 0.35.20 je suis repartie de 0. :$

**Comment by badconker** [comment]
ben sur symfony c'est pas une méthode par fichier : https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Routing/RequestContext.php

**Comment by FlorianPerrot** [comment]
C'est par class symfony, nous nous n'avons pas vraiment de class mais de grosse méthode c'est pour ça que j'ai voulu séparer en méthode. Après c'est vrai qu'il faudrait moins fragmenté certaine partie :$
C'est pour "playing.js" qu'il faut vraiment faire un truc. J'ai envie d'ajouter des fonctionnalités au plugin, mais quand je vois ce mastodonte j'ai peur d'y mettre les doigts ^^

**Comment by badconker** [comment]
Oki, tu peux faire un pull request ? je vais faire ma petite tambouille par la suite. Bon pas toute de suite tout de suite car je pars en vacances et le reste de l'été est mega chargé de boulot. T'as bien testé le .map, ça fonctionne sans soucis ?

**Comment by badconker** [comment]
Par contre, le dossier node_modules n'a pas à être commité normalement ;)

**Comment by badconker** [comment]
Du coup c'est commité : 40c42b7822c0ce61bb87f15c4c899577005230ee
Du coup je clos
